name: grizzly_naive_bayes
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: SERAGUD <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_primitives: # ^0.0.7
    path: ../grizzly_primitives
  grizzly_array: #^1.0.0
    path: ../grizzly_array

dev_dependencies:
  test: ^0.12.0
  grizzly_nlp:
    path: ../grizzly_nlp
